version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-devstore
        environment:
            RABBITMQ_DEFAULT_USER: "devstore"
            RABBITMQ_DEFAULT_PASS: "devstore"

    sql-server:
        image: desenvolvedorio/devstore-sql-server:latest
        container_name: devstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"     

    web-mvc:
        image: desenvolvedorio/devstore-web-mvc-ecommerce:latest
        #container_name: devstore-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/DevStore.WebApp.MVC/Dockerfile
        restart: always            
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:55001
        volumes: 
            - dpkeys:/var/data_protection_keys/         
        depends_on:
            - api-catalog
            - api-identity
            - api-client
            - api-bff-checkout

    api-identity:
        image: desenvolvedorio/devstore-api-identity:latest
        container_name: devstore-api-identity    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Identity.API/Dockerfile  
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55101;http://+55102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            
    api-cart:
        image: desenvolvedorio/devstore-api-cart:latest
        container_name: devstore-api-cart
        build: 
            context: ../src
            dockerfile: ./services/DevStore.ShoppingCart.API/Dockerfile      
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55201;http://+55202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - sql-server         

    api-catalog:
        image: desenvolvedorio/devstore-api-catalog:latest
        container_name: devstore-api-catalog
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Catalog.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55301;http://+55302
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server

    api-client:
        image: desenvolvedorio/devstore-api-client:latest
        container_name: devstore-api-client    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Clients.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55401;http://+55402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - sql-server  

    api-bff-checkout:
        image: desenvolvedorio/devstore-api-bff-checkout:latest
        container_name: devstore-api-bff-checkout
        build: 
            context: ../src
            dockerfile: ./api gateways/DevStore.Bff.Checkout/Dockerfile  
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55501;http://+55502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - api-cart
            - api-billing
            - api-order
            
    api-billing:
        image: desenvolvedorio/devstore-api-billing:latest
        container_name: devstore-api-billing    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Billing.API/Dockerfile
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55601;http://+55602
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identity
            - api-order
            - sql-server
            
    api-order:
        image: desenvolvedorio/devstore-api-order:latest
        container_name: devstore-api-order    
        build: 
            context: ../src
            dockerfile: ./services/DevStore.Orders.API/Dockerfile 
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:55701;http://+55702
            - ASPNETCORE_Kestrel__Certificates__Default__Password=devstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/devstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            - api-identity                    

    devstore-server:
        image: desenvolvedorio/devstore-server:latest
        container_name: devstore-server    
        build: 
            context: ./
            dockerfile: ./nginx/Dockerfile 
        restart: always 
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc

volumes:
    dpkeys:     